### PR TITLE
fix build (correct app name, icons, images, arch)

### PR DESCRIPTION
**Pull request by splix**

### CODE REVIEW

**Comment by splix** [comment]
Linux build still doesn't work, but it may be because I'm trying to build on MacOS. Need to try on TC

**Comment by elaineo** [comment]
MacOS build works for me
`gulp mist --platform darwin`

**Comment by realcodywburns** [comment]
My computer is downloading windows and Linux builds now, I'll report back once I get home and can run some tests

**Comment by realcodywburns** [comment]
Windows 64 build is working.

**Comment by splix** [comment]
awesome! thanks for testing

**Review by elaineo — APPROVED** [review]

**Pull request merged**
