### PR TITLE
Tcbuild fix1

### PR DESCRIPTION
**Pull request by ericsomdahl**
on a fresh checkout, the stale deps in the npm-shrinkwrap.json cause the npm install to pull incorrect versions of various libs and cause failures to generate the DMG artifact

These changes work for the OSX build on TC using Node 6.9.1.  The Linux build still fails but I'm working on that.

### CODE REVIEW

**Comment by splix** [comment]
Hm, on my machine gulp expects `dmg-background.jpg` to be in a dir with other build images. But ok if it works on TC

**Review by splix — APPROVED** [review]

**Comment by ericsomdahl** [comment]
If you look at the gulp task "copy-build-folder-files" you can set what I mean. The dmg-background is listed in the interfaces folder.  The gulp builder fails to generate the final DMG in the absence of that file.

**Comment by splix** [comment]
Yes I see, thanks. It actually can be in both places (:138 vs :139), but `interface` folder seems to be correct place for the image

**Comment by ericsomdahl** [comment]
@codyburns, I pinned the windows TC build to your agent because your system is configured and can build Mist correctly.  Buy the builds fails with a very odd git error.  Can you take a look?

 http://build.ethereumclassic.org/viewLog.html?buildId=646&tab=buildResultsDiv&buildTypeId=Mist_Develop_Windows

**Pull request merged**
